dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
script:
- coverage run ./manage.py test
after_success:
- codecov
deploy:
  provider: heroku
  app: paymepls
  api_key:
    secure: pkMR7T0b9zLbQ1hBYVb06H9BBVOUQyJGkUs95Fa/+nN4ZzmUbNYBi48GctAuAXR8uRuspkz7eMD7AcCdrWdc3xMwShJ79oraJjtNL0oUoQWISRki2I4atm+/rz2tnD10DBmxA14yFo8IFtszlHfcYI1WzH0pRaE+pJlmKmbAaq0iZePgeWREsue5EnihKKoyyVqnyXyRA0tsc35AWv/aH0Iw8xLKsijlCcepDL+aAxkMai3BhYdceuMAKjhGGUmVXlAOTpt3S5khmPtQIJ+5fCIN0YDLYSRSu/ATI1Cx0lgRahWoYMbOqzwzXK2bTgnvcHz8RzYlDqtCJwHp1ZiXSPRUlL389IIG2/tkKJA/Q5DUJD/wpre6PrWxTF+3v28rOKqVlzZUSKG9xOlItSdJH9La9XFhcrdY/iiO5QatDDcvQqBEXePjSAI9d+F0QhjVIjCdNlNZgs5/LkjRX+JQZ2y2NfkpwJiZusx+yqI4txJyR78+K9prR1ObVGKM1ycbykaVwCLYE2EYXNvBkf6jOqfKBk6Ycak/TDl0KOzcVl5QtaOFhB+1Mr4nQW6qUF94g1qKxDx0Fe9FVDC37aAQJJvEThJtgefPffhK8eUXICn1TY/o3eP1gtjzHO6z47niEqT1h5T/9gBSku32BdeatAXGtirjiRJ0iommLieUZOk=
env:
  global:
  - secure: VL9632YpUwvk9VsHhrD+qF3OFXp7kJX1nDmMhCgj5jlnAY1yXkUlOVqzFwcvIFW8xej2ABH9UQmhwymS3+g0PUPkcC8qDezB0bkf/jfe2pcVT96rp6fd1E5PUk76gNA6etQFBBs2l/dczQ6KVh5ZLP7ldmWknDBUvdBQrU1BX0+QUDSNxf4FwbhkMadW01fNOrdF7iYXlxIbGIMZDOuE4ZoJk9bwogbgXGc51I6aNwQBX/KrvjUYmMIcC6u3eH6Xwbpp1Oa6ioSWv5eCDYUfW42JYZoPnoUodyZyS8ubj+zc6Qrj5ZzgX0rbpL2ybpLdXl1RwGJcOTAaJKhCOlYxZE/euDsdh8un2R5xLUo4oHfCdJQ+uUOG1K+9hiiAFwyGBH52HtEc/TQcZC8uctJ4aeVsLuFu8sW8FwDsq1+hqeFRX/S/+7p44OJ8pd9UeSKkyvsz2SwH+1AWk8yCFOR5FWXygMx7ZiW3phczT9auVWtcokzbvTHDo4k6+dE8Diea+XyhdHBcgu0AhUtLLdG2c1IMpa1s8xSMna8X6IeK4Qho/PoKSvYzu8aJ4lBblGm5+v/2ICR0I/OIbknV7O9bcIyVsmVAvQOIpLqYTd38buAMTaYEkULwwgsm6dR4zn6JgynRXpAqzjyzAqSzl0Q6vJHJNfI2hBRSHshRd67rCNs=
  - secure: d5vdxq8Mzpjf6qNyTeRchHh+mM4oG3xCAhcbkFJ5I3Ev8mcJHsPjywprJeJzrDhiVy42kaEqzTShYrdoJj9azSspqPKGuNqgXzf2FSfc5PaU7C9GAC1m0xN10l6ZyqiwWDrh5aiWUJ8nbc4V6Ae7PZw4ScsO2grY+d765dhAPk9Z75AcgeJyTyJk8Do143l4w8a5EVqrSBfbdYJ4aqn1vGoygk6nednrVrdQ/wbciXNkTpbyn6eZWp6hNjk26P1BxfOOUugfgI9T96FjUp7yu69S3Ixshu5YjlfcGHG27u5FaXByQggEhYScfELMUo9qt5Tn7f47IKV7fmgwAIaOqp4SrbHr91woOiN6AGiUlzAueBapizeOiiM7v0Ld7Q53GmfCyciBk3kqDmf1qOYNbzq8nzoPx4ya/QfpvmWexFUGb2erCPyVQmsIVYcPSr8KB/dSK724hSL1H1nZbdOS/iLXuX7fqgW/o04IpVOfQWjb4xI+ScPb+L8iuFaqsHy0/NVPHXcd2wqAHXw8uVeNvErsnIqb8VHcmt0zz3oQw9NXx0v92BXeq4bjJhOXYgOnp6WWUx0RBvwmLLB4ylZY78HcUhx4bDZLo/bgg5pVWm0Rk7vavkb6MAtZrjUNxoGGrK5FsKEkgY7DMc5o5SkAHQ2rUL+7LoT4tpTL4guKdvw=
