# Generated by Django 2.2.1 on 2019-05-23 01:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('ot', 'One Time'), ('rc', 'Recurring')], default='ot', max_length=2)),
                ('due_date', models.DateField()),
                ('recurring_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='myrent', max_length=255)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.Landlord')),
            ],
        ),
    ]
