# Generated by Django 2.2.1 on 2019-05-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_auto_20190522_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='name',
            field=models.CharField(default='myrent', max_length=255),
        ),
    ]
