# Generated by Django 2.2.1 on 2019-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_rent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
