# Generated by Django 2.2.1 on 2019-05-22 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_charge_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
            preserve_default=False,
        ),
    ]
