# Generated by Django 2.2.1 on 2019-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_auto_20190523_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='last_month_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
