# Generated by Django 2.2.1 on 2019-05-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_charge_last_month_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='last_month_paid',
            new_name='num_months_paid',
        ),
    ]
