# Generated by Django 2.2.1 on 2019-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_auto_20190523_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charge',
            name='num_months_paid',
            field=models.IntegerField(default=0),
        ),
    ]
