# Generated by Django 2.2.1 on 2019-05-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_auto_20190523_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
