# Generated by Django 2.2.1 on 2019-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0008_charge_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
