# Generated by Django 2.2.1 on 2019-05-23 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0002_auto_20190523_0124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renter',
            name='rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landlord.Rent'),
        ),
    ]
