# Generated by Django 2.2.1 on 2019-05-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_auto_20190523_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landlord.Rent'),
        ),
    ]
